name: NPM Publish
# attempt to publish every commit to NPM (will only succeed when version is bumped)
on:
  push:
    branches:
      - main
# ensure the cwd is always `/src`
defaults:
  run:
    shell: bash
    working-directory: ./src
# steps
jobs:
  # run tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm test
  # publish to npm (will fail if version not bumped)
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          scope: "@matthewjames/fastify-streamfile"
      - run: |
          cp ../LICENSE ./
          cp ../README.md ./
          npm ci
          npm publish --access=public
          rm ./LICENSE
          rm ./README.md
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
